### ISSUE TITLE
UBJSON broken by matlab `fwrite()` change

### ISSUE THREAD

**Issue by wrgrant** [fangq/jsonlab#81] opened 2022-05-04 01:05 UTC
If I create a UBJSON file via this simple example:
```matlab
% matlab
data.foo = 1.2;

opts = [];
opts.FileName = "test.ubj";
opts.UBJSON = 1;
opts.Endian = 'B';
savebj('', data, opts);
```

Then load it with the `npm` library [`@shelacek/ubjson`](https://www.npmjs.com/package/@shelacek/ubjson) in Node.js like so:

```javascript
// javascript
const fs = require('fs')
const ubjson = require('@shelacek/ubjson')

const data = ubjson.decode(fs.readFileSync("test.ubj"))
```

I will get an `Error: Unexpected type` by that library.

Now here is the interesting part.

If I modify [line 295 in `savebj.m`](https://github.com/fangq/jsonlab/blob/f1332e3a4545a5cd3a433b00435ae011a27d0be7/savebj.m#L295)
From this: `fwrite(fid, json);`
To this: `fwrite(fid, uint8(json));`

Then it works as expected!

I remember this happening a while back but never got around to writing an issue.
I think [these matlab release notes from r2020a](https://www.mathworks.com/help/matlab/release-notes.html?category=data-import-export&rntext=fscanf&startrelease=R2019a&endrelease=R2022a&groupby=release&sortby=descending&searchHighlight=fscanf) may have something to do with it, though they don't specifically note that `fwrite()` was updated.

Also this note from the [matlab `fwrite()` doc page](https://www.mathworks.com/help/matlab/ref/fwrite.html) indicates that they are doing something fancy with the `char` type. Maybe because the string data you generate in the `json` variable is `char` type, matlab is sometimes writing wider characters or something?

![2022-05-03_20h55_01](https://user-images.githubusercontent.com/3092780/166610024-461c6554-6b12-43ec-a825-530def57b39c.png)

Final note - I tried setting the file writing line to this: `fwrite(fid, json, "char*1");` and I got the same error over in javascript!??

I guess I don't understand enough the intricacies of `fwrite()`, but anyways, the above is at least a test situation and how I was able to fix it.

**Comment by fangq** [comment] 2022-05-04 01:52
@wrgrant, thanks for reporting this. Unfortunately I am not able to reproduce this bug. I tested it on Ubuntu 20.04 with MATLAB R2020a, and the output file can be read by the node script, see screenshot below.

what platform are you using? can you do a hexdump to the output file and see if it has anything out of order?

![savebj](https://user-images.githubusercontent.com/226913/166613364-1ea0bedf-5bc4-4014-9a00-6d7044a1ffa3.png)

by the way, you can simply call `saveubjson` instead of `savebj(..., 'ubjson',1, 'endian', 'B')`

**Comment by fangq** [comment] 2022-05-07 03:20
closing because it can not be reproduced.

**Closed by fangq** 2022-05-07 03:20 UTC
Labels: can-not-reproduce
