### ISSUE TITLE
Invalid file identifier error in savejson

### ISSUE THREAD

**Issue by aaronyjze** [fangq/jsonlab#23] opened 2016-03-14 07:42 UTC
Hi, I am new to JSONlab. I ran into an error while trying to run the savejson function on matlab r2015a
My script:

format shortg;
y=0;
while y == 0
    % c = [year month day hour minute seconds]
    c = clock;
    % Rounding every value to an integer
    c = fix(c);
    x.clock = c;
    % accessing the 4th column of c, i.e hours
    x.hours = c(:,4);
    % accessing the 5th column of c, i.e minutes
    x.hours = c(:,5);
    % accessing the 6th column of c, i.e seconds
    x.hours = c(:,6);
    % converting x into JSON and writing as matlabData.json
    savejson('', x, 'data/matlabData.json');
end

Command window:

Error using fwrite
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in savejson (line 160)
	    fwrite(fid,json,'char');

Error in testjson (line 16)
    savejson('', x, 'data/matlabData.json');

Please help! Thanks.

**Comment by fangq** [comment] 2016-03-14 15:34
have you tried the latest git version? we had a couple of bug fixes related to file names

https://github.com/fangq/jsonlab/commit/aa37e53049647b3b8aabf5d21facd030d0afb3d3
https://github.com/fangq/jsonlab/commit/eaca33978dbc7e7f0a96feb16aa078a329cb1ce5

**Comment by aaronyjze** [comment] 2016-03-15 00:08
Ya I am using the latest git version with all the bugs rectified. However, I still run into the above error. Could it be some compatibility issues? I am using R2015a

**Comment by fangq** [comment] 2016-05-02 22:27
sorry for the delay, have been busy.

in matlab, or most other programming language, if you want to save a file under a folder, that folder must exist first.

it appears that your are trying to save matlabData.json under a folder data. It is likely this "data" folder has not been created under your current directly,

you may insert

`mkdir(pwd,'data');
`
before calling savejson. 

I am closing this issue. If you still have trouble, please feel free to reopen.

**Closed by fangq** 2016-05-02 22:27 UTC

**Comment by ketimaBU** [comment] 2017-03-22 14:03
I am facing same problem here , even the folder exists it keeps showing the following error :
Error in savejson (line 160)
fwrite(fid,json,'char');

**Comment by fangq** [comment] 2017-03-22 16:42
@ketimaBU, do you have this issue in the latest version/release or you are using an older version? 

if you still have trouble with the latest version, please post your sample code so that I can reproduce the issue.

**Comment by ketimaBU** [comment] 2017-03-22 16:55
Sorry the problem was only that it was open by other application 
silly problem 
thank you a lot :D
