### ISSUE TITLE
savejson's matlabobject2json does not work in Octave

### ISSUE THREAD

**Issue by girtsf** [fangq/jsonlab#36] opened 2017-04-27 18:39 UTC
When trying to call 'savejson' on a structure containing an object, it explodes with:
```
error: 'properties' undefined near line 441 column 21
error: called from
    savejson>matlabobject2json at line 441 column 19
    savejson>obj2json at line 175 column 8
    savejson at line 140 column 5
```

Looks like Octave (4.2.1 currently) does not implement `properties`.

**Comment by fangq** [comment] 2017-05-31 15:36
@girtsf, can you provide a short script so that I can reproduce this error? what matlab object you were trying to export?

**Comment by girtsf** [comment] 2017-06-01 02:17
@fangq here you go:

TestClass.m:
```matlab
classdef TestClass
    properties
        foo
    end
end
```

json_test.m:
```matlab
test_class = TestClass();
test_class.foo = 42;
savejson('', test_class, 'out.json');
```

MATLAB (R2016b) runs "json_test" without errors and creates out.json as expected.

Octave:
```
octave:1> version
ans = 4.2.1
octave:2> json_test
warning: the 'properties' function is not yet implemented in Octave

Please read `http://www.octave.org/missing.html' to learn how you can
contribute missing functionality.
error: 'properties' undefined near line 441 column 21
error: called from
    savejson>matlabobject2json at line 441 column 19
    savejson>obj2json at line 175 column 8
    savejson at line 140 column 5
    json_test at line 3 column 1
```

**Comment by Andy1978** [comment] 2017-11-01 06:40
@girtsf As the warning tries to tell you, the function "properties" isn't implemented yet in GNU Octave. So to be clear, this isn't a problem with jsonlab.

I had a quick look into the relevant part in GNU Octave and it shouldn't be to hard to implement "properties". You can then add your patch to the patch tracker on savannah so it can be reviewed and merged into core.

Happy hacking!

**Comment by girtsf** [comment] 2017-12-01 19:53
TBH, we kind of gave up on trying to make our stuff work with both Matlab and Octave, at least for now. So getting this working in Octave probably won't be high on my priority list.

Thanks for looking into this!

**Comment by fangq** [comment] 2018-07-12 16:05
sorry for the late response, submitted a request here

https://savannah.gnu.org/bugs/index.php?54294

@Andy1978, I grepped the /usr/share/octave/4.2.2/m folder and only found the class inputParser.m, and reading the related units did not give me any hint how to enumerate properties, any suggestions where to look?

**Comment by fangq** [comment] 2018-11-18 22:51
from the above octave bug I submitted, looks like the octave developers targeted the class property support in octave 5.0. I am closing this tracker, and wait for the upstream to fix the issue.

**Closed by fangq** 2018-11-18 22:51 UTC
Labels: wontfix
